services:
  measurement-api:
    build: .
    ports:
      - '80:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev

  test:
    build: .
    command: npm run test
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=test
    depends_on:
      - measurement-api
